version: '3.8'

services:
    app:
        build:
            context: .  # Current directory as the build context
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www  # Mount the current directory to the container's /var/www
        ports:
            - "8000:8000"   # Expose port 8000 for Laravel app
        depends_on:
            - mysql       # Ensure the mysql service starts before the app
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: root
#        volumes:
#            - mysql-data:/var/lib/mysql  # Persist MySQL data between restarts
        ports:
            - "3306:3306"  # Expose MySQL on port 3306
        networks:
            - app-network

volumes:
    mysql-data:   # Volume for persisting MySQL data

networks:
    app-network:
        driver: bridge
