module.exports = {
  loginPage: {
    emailInput: 'input[name="email"]',
    passwordInput: 'input[name="password"]',
    loginButton: 'button[type="submit"]',
    errorMessage: '.text-negative',
    welcomeMessage: '.welcome-message'
  },

    bookingPage: {
    tourCards: '.tour-card',
    selectTourButton: 'button:has-text("Select Tour")',
    destinationField: '.destination',
    tourNameField: '.tour-name',
    slotsAvailable: '.slots-available',
    ticketsInput: 'input[name="tickets"]',
    ticketHolderInput: 'input[name="ticketHolder"]',
    emailInput: 'input[name="email"]',
    totalPrice: '.total-price',
    bookButton: 'button:has-text("Book Tour")',
    cancelButton: 'button:has-text("Cancel")',
    ticketNumber: '.ticket-number',
    ticketHolder: '.ticket-holder',
    ticketEmail: '.ticket-email',
    ticketTour: '.ticket-tour',
    ticketSlots: '.ticket-slots',
    ticketTotal: '.ticket-total',
    doneButton: 'button:has-text("Done")',
    emailError: '#email + .error-message'
  },

    adminPage: {
    createTourSection: 'a:has-text("Create Tour")',
    tourNameInput: 'input[name="tourName"]',
    descriptionInput: 'textarea[name="description"]',
    destinationInput: 'input[name="destination"]',
    priceInput: 'input[name="price"]',
    slotsInput: 'input[name="slots"]',
    submitButton: 'button:has-text("Submit")',
    cancelButton: 'button:has-text("Cancel")',
    successMessage: '.alert-success',
    errorMessage: '.text-negative',
    toursTable: '.tours-table',
    tableRows: '.tours-table tr',
    tourNameColumn: 'td:nth-child(1)',
    descriptionColumn: 'td:nth-child(2)',
    destinationColumn: 'td:nth-child(3)',
    slotsColumn: 'td:nth-child(4)',
    priceColumn: 'td:nth-child(5)',
    dateColumn: 'td:nth-child(6)',
    actionColumn: 'td:nth-child(7)',
    destinationFilter: 'input[name="destinationFilter"]',
    applyFilterButton: 'button:has-text("Apply Filter")',
    bookingsSection: 'a:has-text("Bookings")',
    ticketsSection: 'a:has-text("Tickets")',
    bookingsTable: '.bookings-table',
    ticketsTable: '.tickets-table',
    tableRows: 'table tr:not(:first-child)',
    bookedByColumn: 'td:nth-child(1)',
    tourNameColumn: 'td:nth-child(2)',
    statusColumn: 'td:nth-child(3)',
    bookingTicketNumberColumn: 'td:nth-child(4)',
    createdAtColumn: 'td:nth-child(5)',
    ticketHolderColumn: 'td:nth-child(1)',
    ticketEmailColumn: 'td:nth-child(2)',
    ticketNumberColumn: 'td:nth-child(3)',
    ticketCreatedAtColumn: 'td:nth-child(4)',
    tourNameFilter: 'input[name="tourFilter"]',
    applyFilterButton: 'button:has-text("Apply Filter")',
    paginationInfo: '.pagination-info'
  },

   adminPanel: {
    rightPanel: '.right-side-panel', // Update with your actual class
    panelTitle: '.panel-header h2',
    closeButton: '.panel-close-button',
    tourNameInput: '.right-side-panel input[name="tourName"]',
    descriptionInput: '.right-side-panel textarea[name="description"]',
    destinationInput: '.right-side-panel input[name="destination"]',
    priceInput: '.right-side-panel input[name="price"]',
    slotsInput: '.right-side-panel input[name="slots"]',
    submitButton: '.right-side-panel button:has-text("Submit")',
    cancelButton: '.right-side-panel button:has-text("Cancel")',
    successMessage: '.alert-success',
    errorMessage: '.text-negative'
  },
  
};